### ISSUE TITLE
Background-color wordt gedefinieerd bij tekst classes

### ISSUE THREAD

**Issue by julia-stevens** [vsheo/look-and-feel-styleguide#11]
Bij de tekst classes, hebben we zowel een `background-color` als een `color`, hierdoor krijgt je tekst een achtergrond kleur, terwijl je juist alleen de kleur aan de tekst wilt meegeven. 

Ik stel voor dat we de `background-color` class verwijderen, zoals hier: 

```css
.text-on-brand {
    /* background-color: var(--text-on-brand); */
    color: var(--text-on-brand);
}
```

Bij de font classes hoeven we dan ook geen `color` te definiëren, want dan kun je in HTML gewoon refereren naar de kleur classes die we voor tekst hebben gemaakt (`text-primary` `text-secondary` `text-on-brand`), dat zou er dan zo uit zien: 

```css
.font-nav-primary {
    /* font: var(--font-primary); */
    /* color: var(--text-on-brand); */
    font-size: var(--font-size-l);
    font-weight: var(--font-weight-baseline);
}
```
