### ISSUE TITLE
Classes van de zenders samenvoegen in één class

### ISSUE THREAD

**Issue by julia-stevens** [vsheo/look-and-feel-styleguide#18]
Ik heb maandag feedback gekregen van @Sidstumple op onze stylesheet: 

We kunnen onze classes per zender samenvoegen, omdat de custom properties per zender allemaal anders zijn en deze later overschreven worden.  Zie voorbeeld: 

```css
.veronica {
    --brand-primary: #0091FF; 
    --brand-secondary: #E60063;
    --brand-footer: #011564;
    --background-neutral: #fafafa;
    --brand-neutral: #ffffff;
    --text-primary: #000000;
    --text-secondary: #8B8B8B;
    --text-on-brand: #ffffff;   
}
```

In HTML worden de classes dan ook een stuk leesbaarder, bijvoorbeeld: een `nav` met de primary achtergrond kleur: 

```html
<!-- NIEUWE class namen -->
<nav class="primary veronica"></nav>

<!-- OUDE class namen -->
<nav class="primary veronica-primary"></nav>
```

Wat vinden jullie? @vsheo @Sebastiaan-hva @poormoa00
